version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.11-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run: echo "Started Build"
      - run: npm run test
      - run: npx ng build

      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: dist
          paths:
            - blog

  deploy:
    docker:
    - image: circleci/python:2.7-jessie


    steps:
      - run: echo "Installing AWS CLI"
      - run: sudo pip install awscli
      - attach_workspace:
          at: dist
      - run: echo "Started Deployment"
      - run: aws s3 sync --acl public-read dist/blog s3://$BUCKET_NAME --acl=public-read

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
