version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.11
    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: npm install
    - run: npx ng test
    - run: echo "Started Build"
    - run: npx ng build

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - store_artifacts:
        path: dist/blog
        destination: blog

  deploy:
    docker:
    - image: circleci/node:8.11
    working_directory: ~/repo

    steps:
    - run: echo "Started Deployment"
    - run: aws s3 sync --acl public-read dist/blog s3://$BUCKET_NAME --acl=public-read

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
